/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    screenings: Screening;
    'landing-pages': LandingPage;
    cast: Cast;
    credits: Credit;
    reviews: Review;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    screenings: ScreeningsSelect<false> | ScreeningsSelect<true>;
    'landing-pages': LandingPagesSelect<false> | LandingPagesSelect<true>;
    cast: CastSelect<false> | CastSelect<true>;
    credits: CreditsSelect<false> | CreditsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'press-page': PressPage;
    'share-page': SharePage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'press-page': PressPageSelect<false> | PressPageSelect<true>;
    'share-page': SharePageSelect<false> | SharePageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "screenings".
 */
export interface Screening {
  id: number;
  /**
   * e.g. "SXSW World Premiere" or "Private Cast & Crew Screening"
   */
  title: string;
  /**
   * Display date, e.g. "MAR 12"
   */
  date: string;
  /**
   * e.g. "9:45 PM"
   */
  time: string;
  /**
   * e.g. "ALAMO LAMAR 7"
   */
  venue: string;
  /**
   * e.g. "AUSTIN, TX"
   */
  location: string;
  /**
   * Used to determine if screening is upcoming or past
   */
  eventDate: string;
  /**
   * Groups screenings on the page, e.g. "SXSW 2026", "Cannes 2026"
   */
  eventGroup: string;
  /**
   * Optional note, e.g. "*Q&A to follow with cast and filmmakers"
   */
  note?: string | null;
  /**
   * Public screenings appear on /screenings. Private ones only on landing pages.
   */
  visibility: 'public' | 'private';
  /**
   * How tickets/RSVP are handled for this screening
   */
  ticketingType: 'external' | 'luma' | 'custom';
  /**
   * URL to external ticket page (SXSW, Cannes, etc.) or custom link
   */
  ticketUrl?: string | null;
  /**
   * Full Luma event URL (e.g. https://lu.ma/abc123) — used to render the RSVP embed widget
   */
  lumaEventUrl?: string | null;
  /**
   * For private screenings, link to the landing page where this screening appears
   */
  linkedLandingPage?: (number | null) | LandingPage;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Private, unlisted pages for invited audiences. Not crawlable by search engines.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages".
 */
export interface LandingPage {
  id: number;
  title: string;
  /**
   * URL path: /p/{slug}. Use lowercase, hyphens only.
   */
  slug: string;
  /**
   * Optional subtitle or tagline for the page
   */
  subtitle?: string | null;
  /**
   * YouTube video ID for the teaser (e.g. RaeZ8LUgFxA)
   */
  teaserVideoId?: string | null;
  /**
   * Optional custom thumbnail for the video player
   */
  teaserVideoThumbnail?: (number | null) | Media;
  /**
   * Main content blocks for the landing page — supports headings, links, images, lists, and blockquotes
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Link private screenings to this page. Their Luma RSVP embeds will render inline.
   */
  screenings?: (number | Screening)[] | null;
  /**
   * Fallback CTA button label if no screenings are linked
   */
  ctaLabel?: string | null;
  /**
   * Fallback CTA URL if no screenings are linked (e.g. a direct Luma link)
   */
  ctaUrl?: string | null;
  /**
   * Only published pages are accessible. Unpublished returns 404.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cast".
 */
export interface Cast {
  id: number;
  /**
   * Character name, e.g. "Ben Garza"
   */
  characterName: string;
  /**
   * Credit label, e.g. "Performed by"
   */
  performedBy: string;
  /**
   * Actor name, e.g. "David Ramirez"
   */
  actorName: string;
  /**
   * Optional link (e.g. IMDb profile)
   */
  actorUrl?: string | null;
  primaryImage: number | Media;
  hoverImage: number | Media;
  /**
   * Optional character quote
   */
  quote?: string | null;
  /**
   * Display order (lower = first)
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credits".
 */
export interface Credit {
  id: number;
  /**
   * e.g. "Director", "Writers", "Producers"
   */
  role: string;
  /**
   * Person or people in this role
   */
  name: string;
  /**
   * Display order (lower = first)
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  /**
   * e.g. "SXSW Best of Texas Award"
   */
  award: string;
  /**
   * e.g. "Winner: Stages directed by Ryan Booth"
   */
  winner?: string | null;
  /**
   * Review quote or award description
   */
  quote?: string | null;
  /**
   * Laurel or award badge image (upload to Media)
   */
  laurelImage?: (number | null) | Media;
  /**
   * Fallback: public path to laurel image if not using Media upload (e.g. /Best of Texas Award_White.png)
   */
  laurelImageUrl?: string | null;
  /**
   * Display order (lower = first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'screenings';
        value: number | Screening;
      } | null)
    | ({
        relationTo: 'landing-pages';
        value: number | LandingPage;
      } | null)
    | ({
        relationTo: 'cast';
        value: number | Cast;
      } | null)
    | ({
        relationTo: 'credits';
        value: number | Credit;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "screenings_select".
 */
export interface ScreeningsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  time?: T;
  venue?: T;
  location?: T;
  eventDate?: T;
  eventGroup?: T;
  note?: T;
  visibility?: T;
  ticketingType?: T;
  ticketUrl?: T;
  lumaEventUrl?: T;
  linkedLandingPage?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages_select".
 */
export interface LandingPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  teaserVideoId?: T;
  teaserVideoThumbnail?: T;
  content?: T;
  screenings?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cast_select".
 */
export interface CastSelect<T extends boolean = true> {
  characterName?: T;
  performedBy?: T;
  actorName?: T;
  actorUrl?: T;
  primaryImage?: T;
  hoverImage?: T;
  quote?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credits_select".
 */
export interface CreditsSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  award?: T;
  winner?: T;
  quote?: T;
  laurelImage?: T;
  laurelImageUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * YouTube video ID for the hero background (e.g. RaeZ8LUgFxA)
   */
  heroVideoId?: string | null;
  /**
   * Fallback carousel images when video isn't playing
   */
  heroImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Award laurels displayed above the title. Drag to reorder. They auto-shrink as more are added.
   */
  laurels?:
    | {
        image: number | Media;
        /**
         * Optional link URL for this laurel
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Film synopsis / logline shown in the hero
   */
  logline: string;
  directedBy: string;
  year: string;
  /**
   * e.g. "94 MIN"
   */
  runtime: string;
  aboutHeading?: string | null;
  /**
   * Extended film description paragraphs
   */
  aboutContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Director's statement / quote block
   */
  directorNote?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  directorName?: string | null;
  /**
   * Show a condensed upcoming screenings section on the homepage linking to /screenings
   */
  showScreeningsPreview?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-page".
 */
export interface PressPage {
  id: number;
  /**
   * Introduction text at the top of the press page
   */
  introText?: string | null;
  /**
   * Key/value pairs for film information (Title, Year, Runtime, etc.)
   */
  filmFacts?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Press material download links
   */
  downloads?:
    | {
        title: string;
        description?: string | null;
        /**
         * Link URL (e.g. /share#press-promotional)
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "share-page".
 */
export interface SharePage {
  id: number;
  /**
   * Introduction text at the top of the share page
   */
  introText?: string | null;
  /**
   * Usage guidelines content (two-column on desktop)
   */
  usageGuidelines?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Press & promotional images (posters, social assets, key art)
   */
  promotionalAssets?:
    | {
        image: number | Media;
        /**
         * Optional label for the asset
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Production still images for editorial use
   */
  productionStills?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Canonical site URL (no trailing slash)
   */
  siteUrl: string;
  /**
   * Google Analytics 4 measurement ID (e.g. G-5KDEP34PFL)
   */
  googleAnalyticsId?: string | null;
  /**
   * Contact information shown in footer and press page
   */
  contactEntries?:
    | {
        /**
         * Role title, e.g. "Distributor", "Publicity Contact"
         */
        title: string;
        /**
         * Organization name
         */
        org?: string | null;
        name?: string | null;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Social media links
   */
  socialLinks?:
    | {
        platform: 'instagram' | 'twitter' | 'imdb' | 'youtube' | 'facebook' | 'other';
        url: string;
        /**
         * Display label (optional, defaults to platform name)
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroVideoId?: T;
  heroImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  laurels?:
    | T
    | {
        image?: T;
        link?: T;
        id?: T;
      };
  logline?: T;
  directedBy?: T;
  year?: T;
  runtime?: T;
  aboutHeading?: T;
  aboutContent?: T;
  directorNote?: T;
  directorName?: T;
  showScreeningsPreview?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-page_select".
 */
export interface PressPageSelect<T extends boolean = true> {
  introText?: T;
  filmFacts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  downloads?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "share-page_select".
 */
export interface SharePageSelect<T extends boolean = true> {
  introText?: T;
  usageGuidelines?: T;
  promotionalAssets?:
    | T
    | {
        image?: T;
        label?: T;
        id?: T;
      };
  productionStills?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteUrl?: T;
  googleAnalyticsId?: T;
  contactEntries?:
    | T
    | {
        title?: T;
        org?: T;
        name?: T;
        email?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}